// AUTO-GENERATED by scripts/build-tools.ts — do not edit.
// 构建期排除的全局工具名单（GEBAI_BUILD_EXCLUDE_TOOLS 烘焙）：被排除的工具不注册不暴露。
// 提交版本保持空名单（构建期裁剪产物不入库）；裁剪构建后本文件为脏属预期，下次常规构建自动恢复全量。
export const EXCLUDED_GLOBAL_TOOLS: string[] = []
