// AUTO-GENERATED by scripts/build-env-embed.ts — do not edit.
// 构建期内置环境变量默认值（GEBAI_BUILD_EMBED_ENV=1 时从 .env 烘焙 GEBAI_LLM_ 与 GEBAI_VISION_ 前缀模型配置）。
// 仅作启动默认（运行时环境变量与前端/任务级 env 优先）；**非空态含密钥明文，绝不提交**。
export const EMBEDDED_ENV_DEFAULTS: Record<string, string> = {}
