/**
 * 构建时生成全局工具排除清单（`src/core/tools-excluded.generated.ts`）。
 *
 * 构建期排除指定（环境变量，二进制形态无法改源码，须在构建时定死）：
 * - `GEBAI_BUILD_EXCLUDE_TOOLS`：逗号分隔的全局工具名排除清单（缺省 = 空清单，全部注册）。
 *   被排除的工具不注册进总Agent 全局工具集（schema 不可见、调用报未知工具）；agent_run 新会话
 *   内建编排工具（flow/tool_schemas/js）与 index.ts 的 vision 注册同规则过滤（isGlobalToolExcluded）。
 *   语义注意：这是**能力裁剪**——工具实现与全局工具表同模块，代码仍会打包（无法摇树）；体积裁剪
 *   主要来自子Agent 包含清单（GEBAI_BUILD_SUBAGENTS）与内嵌产物跳过。
 * - 清单中的未知名字直接报错退出（防构建产物静默缺失），并列出可用名单辅助修正。
 *
 * 消费方：`src/core/tools.ts` **静态导入**（运行时读文件在 bun --compile 单文件形态不可行）——因此生成文件
 * 提交默认空名单入库（与 subagents.bundle 的 gitignore 策略不同），裁剪构建后为脏属预期，勿提交裁剪态。
 */
import { writeFileSync } from "node:fs"
import { join } from "node:path"
import { createAllGlobalTools } from "../src/core/tools"

const root = join(import.meta.dirname, "..") // scripts/ 上一级 = packages/server
const outFile = join(root, "src", "core", "tools-excluded.generated.ts")

/** 逗号分隔环境变量 → 名单（空值 = 未指定）。 */
const nameList = (v: string | undefined): string[] =>
  (v ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)

const excludeNames = [...new Set(nameList(process.env.GEBAI_BUILD_EXCLUDE_TOOLS))]

// 清单校验：对全量名单校验（连续两次不同排除清单的构建，上次被排除的名字这次须仍可指定）
const known = new Set([...Object.keys(createAllGlobalTools()), "vision"]) // vision 在 index.ts 单独注册，同样可排除
const unknown = excludeNames.filter((n) => !known.has(n))
if (unknown.length) {
  console.error(`[build-tools] 未知全局工具名: ${unknown.join(", ")}（可用: ${[...known].sort().join(", ")}）`)
  process.exit(1)
}

const lines = [
  "// AUTO-GENERATED by scripts/build-tools.ts — do not edit.",
  "// 构建期排除的全局工具名单（GEBAI_BUILD_EXCLUDE_TOOLS 烘焙）：被排除的工具不注册不暴露。",
  "// 提交版本保持空名单（构建期裁剪产物不入库）；裁剪构建后本文件为脏属预期，下次常规构建自动恢复全量。",
  `export const EXCLUDED_GLOBAL_TOOLS: string[] = ${JSON.stringify(excludeNames)}`,
  "",
]
writeFileSync(outFile, lines.join("\n"))
console.log(`[build-tools] excluded ${excludeNames.length} global tools${excludeNames.length ? ` (${excludeNames.join(", ")})` : ""} -> ${outFile}`)
