/**
 * 构建时全局工具预处理（两件事）：
 *
 * 1. 生成工具 bundle 注册表（`src/core/tools/bundle.generated.ts`）——dist / bun --compile 形态下
 *    `core/tools/` 源码目录与动态 import 均不可用，构建前把所有工具文件的 `globalTools` 注册条目以
 *    静态 import 聚合成注册表，随 bundle 内联进产物（与 build-subagents 的 subagents.bundle 同机制，
 *    实现全局工具「丢文件零注册」的构建侧通道；dev 形态由 tools/index.ts 运行时扫描本目录）。
 *    该文件为生成产物，已 gitignore，勿手改。
 *
 * 2. 生成构建期排除清单（`src/core/tools-excluded.generated.ts`）：
 *    - `GEBAI_BUILD_EXCLUDE_TOOLS`：逗号分隔的全局工具名排除清单（缺省 = 空清单，全部注册）。
 *      被排除的工具不注册进总Agent 全局工具集（schema 不可见、调用报未知工具）；agent_run 新会话
 *      内建编排工具（tool_schemas/js）与 index.ts 的 vision 注册同规则过滤（isGlobalToolExcluded）。
 *      语义注意：这是**能力裁剪**——工具实现与注册条目同模块，代码仍会打包（无法摇树）；体积裁剪
 *      主要来自子Agent 包含清单（GEBAI_BUILD_SUBAGENTS）与内嵌产物跳过。
 *    - 清单中的未知名字直接报错退出（防构建产物静默缺失），并列出可用名单辅助修正。
 *    - 消费方：`src/core/tools/index.ts` **静态导入**（运行时读文件在 bun --compile 单文件形态不可行）——
 *      因此生成文件提交默认空名单入库（与 bundle 的 gitignore 策略不同），裁剪构建后为脏属预期，勿提交裁剪态。
 */
import { readFileSync, writeFileSync } from "node:fs"
import { readdir } from "node:fs/promises"
import { join } from "node:path"
import { createAllGlobalTools } from "../src/core/tools"

const root = join(import.meta.dirname, "..") // scripts/ 上一级 = packages/server
const toolsDir = join(root, "src", "core", "tools")
const bundleOut = join(toolsDir, "bundle.generated.ts")
const excludedOut = join(root, "src", "core", "tools-excluded.generated.ts")

// ---- 1. 工具 bundle 注册表 ----
const entries = await readdir(toolsDir, { withFileTypes: true })
const files: string[] = []
for (const e of entries) {
  if (!e.isFile() || !e.name.endsWith(".ts") || e.name.endsWith(".test.ts")) continue
  if (e.name === "index.ts" || e.name === "shared.ts" || e.name === "bundle.generated.ts") continue
  // 注册文件判定：内容须导出 `globalTools`（辅助文件不收录，与运行时扫描同判定）
  if (/export\s+const\s+globalTools\b/.test(readFileSync(join(toolsDir, e.name), "utf8"))) files.push(e.name)
}
files.sort((a, b) => a.localeCompare(b))
const bundleLines = [
  "// AUTO-GENERATED by scripts/build-tools.ts — do not edit.",
  'import type { GlobalToolEntry } from "./shared"',
  ...files.map((f) => `import { globalTools as entries_${f.slice(0, -3)} } from "./${f.slice(0, -3)}"`),
  "",
  `export const bundledToolEntries: GlobalToolEntry[] = [${files.map((f) => `...entries_${f.slice(0, -3)}`).join(", ")}]`,
  "",
]
writeFileSync(bundleOut, bundleLines.join("\n"))
console.log(`[build-tools] bundled ${files.length} tool files (${files.map((f) => f.slice(0, -3)).join(", ")}) -> ${bundleOut}`)

// ---- 2. 排除清单 ----
/** 逗号分隔环境变量 → 名单（空值 = 未指定）。 */
const nameList = (v: string | undefined): string[] =>
  (v ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)

const excludeNames = [...new Set(nameList(process.env.GEBAI_BUILD_EXCLUDE_TOOLS))]

// 清单校验：对全量名单校验（连续两次不同排除清单的构建，上次被排除的名字这次须仍可指定）
const known = new Set([...Object.keys(createAllGlobalTools()), "vision"]) // vision 在 index.ts 单独注册，同样可排除
const unknown = excludeNames.filter((n) => !known.has(n))
if (unknown.length) {
  console.error(`[build-tools] 未知全局工具名: ${unknown.join(", ")}（可用: ${[...known].sort().join(", ")}）`)
  process.exit(1)
}

const lines = [
  "// AUTO-GENERATED by scripts/build-tools.ts — do not edit.",
  "// 构建期排除的全局工具名单（GEBAI_BUILD_EXCLUDE_TOOLS 烘焙）：被排除的工具不注册不暴露。",
  "// 提交版本保持空名单（构建期裁剪产物不入库）；裁剪构建后本文件为脏属预期，下次常规构建自动恢复全量。",
  `export const EXCLUDED_GLOBAL_TOOLS: string[] = ${JSON.stringify(excludeNames)}`,
  "",
]
writeFileSync(excludedOut, lines.join("\n"))
console.log(`[build-tools] excluded ${excludeNames.length} global tools${excludeNames.length ? ` (${excludeNames.join(", ")})` : ""} -> ${excludedOut}`)
