/**
 * 构建时生成子 Agent bundle 注册表（`src/core/subagents.bundle.generated.ts`）。
 *
 * 背景：`discover()` 在 dev 模式下运行时扫描 `src/sub-agents/` 并动态 import；
 * 但 dist/bun --compile 产物中源码目录与动态 import 路径均不可用。
 * 本脚本在构建前把所有子 Agent 定义（含其导入的 .md 提示词）以静态 import
 * 聚合成注册表，随 bundle 一起内联进产物，实现子 Agent「打包进二进制」。
 *
 * 该文件为生成产物，已 gitignore，勿手改。
 */
import { readdir } from "node:fs/promises"
import { join } from "node:path"
import { writeFileSync, readFileSync } from "node:fs"
import { parseSubAgentMd } from "../src/core/sub-agent-md"

const root = join(import.meta.dirname, "..") // scripts/ 上一级 = packages/server
const srcDir = join(root, "src", "sub-agents")
const outFile = join(root, "src", "core", "subagents.bundle.generated.ts")

/** 定义文件判定：内容须导出 `def`（辅助文件如 desktop_tools.ts 不收录）。 */
function isDefFile(p: string): boolean {
  try {
    return /export\s+const\s+def\b/.test(readFileSync(p, "utf8"))
  } catch {
    return false
  }
}

const entries = await readdir(srcDir, { withFileTypes: true })
/** 子Agent 命名规则（DESIGN：仅限小写字母/数字/下划线）；不合规条目跳过并告警，防生成非法标识符。 */
function validName(name: string): boolean {
  if (/^[a-z0-9_]+$/.test(name)) return true
  console.warn(`[build-subagents] 跳过不合规子Agent 名: ${name}（须匹配 [a-z0-9_]+）`)
  return false
}
/** bundle 条目：静态 import 行（ts 定义）或内联 def 对象行（纯 md 定义）。 */
const defs: Array<{ name: string; line: string }> = []
const seen = new Set<string>()
for (const e of entries) {
  const base = e.name
  if (e.isDirectory()) {
    if (seen.has(base) || !validName(base)) continue
    seen.add(base)
    const tsEntry = join(srcDir, base, `${base}.ts`)
    if (isDefFile(tsEntry)) {
      defs.push({ name: base, line: `import { def as subAgent_${base} } from "../sub-agents/${base}/${base}"` })
    } else {
      // 纯提示词简化定义：{dir}.md 单独存在，内联为 def 对象（description/systemPrompt 转义嵌入）
      try {
        const md = readFileSync(join(srcDir, base, `${base}.md`), "utf8")
        const { description, systemPrompt } = parseSubAgentMd(base, md)
        defs.push({
          name: base,
          line: `const subAgent_${base}: SubAgentDef = { name: ${JSON.stringify(base)}, description: ${JSON.stringify(description)}, systemPrompt: ${JSON.stringify(systemPrompt)} }`,
        })
      } catch {
        console.warn(`[build-subagents] 跳过 ${base}：{${base}.md} 缺失或不可读`)
      }
    }
  } else if (e.isFile() && e.name.endsWith(".ts") && !e.name.endsWith(".test.ts")) {
    const name = e.name.slice(0, -3)
    if (seen.has(name) || !validName(name)) continue
    seen.add(name)
    if (isDefFile(join(srcDir, e.name))) defs.push({ name, line: `import { def as subAgent_${name} } from "../sub-agents/${name}"` })
  }
}
defs.sort((a, b) => a.name.localeCompare(b.name))

const lines = [
  "// AUTO-GENERATED by scripts/build-subagents.ts — do not edit.",
  'import type { SubAgentDef } from "./types"',
  ...defs.map((d) => d.line),
  "",
  `export const bundledDefs: SubAgentDef[] = [${defs.map((d) => `subAgent_${d.name}`).join(", ")}]`,
  "",
]
writeFileSync(outFile, lines.join("\n"))
console.log(`[build-subagents] bundled ${defs.length} sub-agents -> ${outFile}`)

/**
 * 子Agent 运行时资源复制：playwright 子Agent 的 node 桥接驱动（driver.mjs）不能被
 * bun build 内联（需保持独立文件供 node 子进程运行），构建时复制到 dist/ 与产物同目录。
 * 幂等：typecheck 等场景下 dist/ 不存在也会创建（产物目录已 gitignore）。
 */
const driverSrc = join(srcDir, "playwright", "driver.mjs")
const distDir = join(root, "dist")
try {
  const { copyFile, mkdir } = await import("node:fs/promises")
  await mkdir(distDir, { recursive: true })
  await copyFile(driverSrc, join(distDir, "driver.mjs"))
  console.log(`[build-subagents] copied playwright driver -> ${join(distDir, "driver.mjs")}`)
} catch (err) {
  console.warn(`[build-subagents] playwright driver 复制失败（playwright 子Agent 在 dist 模式将不可用）: ${err instanceof Error ? err.message : err}`)
}
