/**
 * 构建期内置环境变量默认值（`src/core/env-embedded.generated.ts`）。
 *
 * 构建期指定（环境变量）：
 * - `GEBAI_BUILD_EMBED_ENV=1`：从仓库根 `.env`（+ 进程环境变量）收集 GEBAI_LLM_ 与 GEBAI_VISION_ 前缀
 *   的**模型配置**，烘焙为启动默认值——发行裁剪构建产出「开箱即用」
 *   二进制：接收方无需配置模型即可使用；运行时同名环境变量与前端/任务级 env 仍可覆盖内置默认。
 * - 缺省（未设置）：写空对象（还原态）。
 *
 * 消费方：`src/index.ts` startServer 顶部经 `applyEmbeddedEnvDefaults` 填充进程环境未设置的键。
 * 文件策略与 tools-excluded.generated.ts 一致：**提交默认空对象入库**（缺省态无密钥，类型检查/测试
 * 依赖其存在）；内置构建后为**脏态（含密钥明文）属预期，绝不提交**——调用方构建脚本编译完成后
 * 须立即重跑本脚本还原空态。
 *
 * 安全注意：内置值随二进制分发，**可被持有二进制者提取**（明文打进产物）——仅适用于受信任小范围
 * 分发，建议使用低额度专用 Key；打印仅输出变量名，绝不输出值。
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs"
import { join } from "node:path"

const serverRoot = join(import.meta.dirname, "..") // scripts/ 上一级 = packages/server
const repoRoot = join(serverRoot, "..", "..")
const outFile = join(serverRoot, "src", "core", "session", "env-embedded.generated.ts")
const envFile = join(repoRoot, ".env")

/** 内置范围：仅模型配置前缀（GEBAI_LLM_ 与 GEBAI_VISION_ 前缀），不内置端口/沙箱/项目路径等部署配置。 */
const EMBED_PREFIXES = ["GEBAI_LLM_", "GEBAI_VISION_"]

const collect: Record<string, string> = {}

if (process.env.GEBAI_BUILD_EMBED_ENV === "1") {
  // 仓库根 .env 显式解析（Bun 亦会自动加载，显式解析保证确定性）
  if (existsSync(envFile)) {
    for (const raw of readFileSync(envFile, "utf8").split(/\r?\n/)) {
      const line = raw.trim()
      if (!line || line.startsWith("#")) continue
      const eq = line.indexOf("=")
      if (eq <= 0) continue
      const key = line.slice(0, eq).trim()
      let value = line.slice(eq + 1).trim()
      // 去包裹引号
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1)
      }
      if (value) collect[key] = value
    }
  }
  // 进程环境变量并入（Bun 自动加载的 .env 与系统注入同源；显式环境优先于文件解析）
  for (const [k, v] of Object.entries(process.env)) {
    if (v) collect[k] = v
  }
}

const embedded: Record<string, string> = {}
for (const [k, v] of Object.entries(collect)) {
  if (EMBED_PREFIXES.some((p) => k.startsWith(p)) && v) embedded[k] = v
}

const lines = [
  "// AUTO-GENERATED by scripts/build-env-embed.ts — do not edit.",
  "// 构建期内置环境变量默认值（GEBAI_BUILD_EMBED_ENV=1 时从 .env 烘焙 GEBAI_LLM_ 与 GEBAI_VISION_ 前缀模型配置）。",
  "// 仅作启动默认（运行时环境变量与前端/任务级 env 优先）；**非空态含密钥明文，绝不提交**。",
  `export const EMBEDDED_ENV_DEFAULTS: Record<string, string> = ${JSON.stringify(embedded)}`,
  "",
]
writeFileSync(outFile, lines.join("\n"))
console.log(
  `[build-env-embed] ${process.env.GEBAI_BUILD_EMBED_ENV === "1" ? `内置 ${Object.keys(embedded).length} 项模型配置: ${Object.keys(embedded).sort().join(", ") || "无（.env 无匹配前缀变量）"}` : "空态（还原）"} -> ${outFile}`,
)
